import console from 'console'
import {buffer,util} from 'node'
console.debug('buffer is a =>', typeof buffer)
console.debug('buffer.atob is a =>', typeof buffer.atob)
console.debug('buffer.btoa is a =>', typeof buffer.btoa)
console.debug('buffer.byteLengthUtf8 is a =>', typeof buffer.byteLengthUtf8)
console.debug('buffer.compare is a =>', typeof buffer.compare)
console.debug('buffer.compareOffset is a =>', typeof buffer.compareOffset)
console.debug('buffer.copy is a =>', typeof buffer.copy)
console.debug('buffer.indexOfBuffer is a =>', typeof buffer.indexOfBuffer)
console.debug('buffer.indexOfNumber is a =>', typeof buffer.indexOfNumber)
console.debug('buffer.indexOfString is a =>', typeof buffer.indexOfString)
console.debug('buffer.swap16 is a =>', typeof buffer.swap16)
console.debug('buffer.swap32 is a =>', typeof buffer.swap32)
console.debug('buffer.swap64 is a =>', typeof buffer.swap64)
console.debug('buffer.kMaxLength is =>', buffer.kMaxLength)
console.debug('buffer.kStringMaxLength is =>', buffer.kStringMaxLength)
console.debug('util.constants.ALL_PROPERTIES is =>', util.constants.ALL_PROPERTIES)
console.debug('util.constants.ONLY_ENUMERABLE is =>', util.constants.ONLY_ENUMERABLE)
console.debug('util.getOwnNonIndexProperties is a =>', typeof util.getOwnNonIndexProperties)
console.debug('util.isInsideNodeModules is a =>', typeof util.isInsideNodeModules)
